name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls
    - run: sudo apt-get install npm
    - run: sudo npm install -g libdragon
    - run: sudo libdragon download
    - run: sudo libdragon start
    - run: sudo libdragon make
